'use client';
import { useState } from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import HamburgerMenu from "../components/HamburgerMenu";
import { ClosetProvider } from '../context/ClosetContext'; // これを追加

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadataはサーバーコンポーネントでしか使えないので、ここでは定義しない
// 必要であれば、このコンポーネントをラップするサーバーコンポーネントで定義する
// export const metadata = {
//   title: "✨ガチ可愛いクローゼットアプリ✨",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <html lang="ja">
      <head>
        <title>✨ガチ可愛いクローゼットアプリ✨</title>
        <meta name="description" content="Your one and only fashion assistant" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClosetProvider> {/* これで全体をラップ！ */}
          <HamburgerMenu onToggle={toggleSidebar} isOpen={isSidebarOpen} />
          <Sidebar isOpen={isSidebarOpen} />
          <main className={`main-content ${isSidebarOpen ? 'sidebar-open' : ''}`}>
            {children}
          </main>
        </ClosetProvider>
      </body>
    </html>
  );
}
